name: "Overlay C++ Build"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: |
          Git ref to build. Empty = latest master.
          Examples: v0.2.1 (release tag)  |  ec2b9b0 (commit SHA)  |  master (branch)
        type: string
        required: false
        default: ''

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      devel: "true"
      build-id: 'test'
      ref: ${{ inputs.ref }}
      patch-type: 'overlay-cpp'
    secrets: inherit
